include ../../compile_config.mk
include ../../release_version.mk

############################################################################
# Beginming of Developer Modification 
############################################################################

# for building program
application_NAME        :=  
# for building library
library_NAME            := libbar

# share library version option
SHARED_LIB_VERSION      := $(RELEASE_VERSION)

project_SRCS			:= bar.c

# build option
project_DEPENDS_DIRS    :=  
project_INCLUDE_DIRS    := 
project_LIBRARY_DIRS    := 

project_STATIC_LIBS     := 
project_SHARED_LIBS     := 

CFLAGS      += -Wall -fPIC
CPPFLAGS    += 
LDFLAGS     +=  
############################################################################
# End of Developer Modification 
############################################################################

include ../../compile_rule.mk

